---
vault: http://localhost:8200
hostGroupPolicies:
  - host-oidc-token
  - host-read-kv
  - host-sign-tls-certificate
  - host-sign-ssh-certificate
  - host-read-prod-certificates
  - default
hostGroupName: hosts
hostMountAccessor: auth_approle_0651e1da
hosts:
  one-host:
  two-hosts:
